//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBricksWeb.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerActivationLog> CustomerActivationLogs { get; set; }
        public virtual DbSet<DistributorPartner> DistributorPartners { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Lead> Leads { get; set; }
        public virtual DbSet<LeadModule> LeadModules { get; set; }
        public virtual DbSet<Licensing> Licensings { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Po> Poes { get; set; }
        public virtual DbSet<Poc> Pocs { get; set; }
        public virtual DbSet<PocModule> PocModules { get; set; }
        public virtual DbSet<PoModule> PoModules { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ZipUpload> ZipUploads { get; set; }
    }
}
