//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBricksWeb.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Po
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public string PartnerName { get; set; }
        public string PODate { get; set; }
        public Nullable<int> PocId { get; set; }
        public string PocName { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public string QualifiedDomainName { get; set; }
        public string PublicIp { get; set; }
        public string PODescription { get; set; }
        public Nullable<int> TotalModuleAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string Status { get; set; }
        public string CompanyName { get; set; }
        public string TechContPersonNameOne { get; set; }
        public string TechContPersonEmailOne { get; set; }
        public string TechContPersonPhoneOne { get; set; }
        public string TechContPersonNameTwo { get; set; }
        public string TechContPersonEmailTwo { get; set; }
        public string TechContPersonPhoneTwo { get; set; }
    }
}
